### ISSUE TITLE
util.lua 中有个bug

### ISSUE THREAD

**Issue by xumenghe** [appwilldev/moochine#2]
第46行： global['MOOCHINE_APP']=appname

应改为： global['MOOCHINE_APP']=app_name

**Comment by catlovemouse** [comment]
谢谢你指出bug，我们已经更改：

https://github.com/appwilldev/moochine/commit/9cafefad5041b1201cfd6bd5272671500d1dc04b

global['MOOCHINE_APP']=app_name
